### ISSUE TITLE
Unable tot Run command

### ISSUE THREAD

**Issue by JoshTheTofu** [red031000/ktane-DynamicMissionGenerator#24]
Hi Guys

I am unable to run any command and create any bomb.

I am trying to run a bomb of just Simon Says so I enter the command 6*Simon but when I click run or use CTRL+Enter, nothing happens.

I have tried other commands and saving the missions before running but it still doesn't work. 

I am playing on Linux (I have also tried running the Windows version of the game via Proton).

**Comment by sykesjd** [comment]
Able to provide some more detail here - I've been having the same problem. I went to the KTANE log and found the following exception being thrown on attempting to run:
```
[Unity] Exception: ArgumentNullException: Argument cannot be null.
Parameter name: first 
at: System.Linq.Check.FirstAndSecond (System.Object first, System.Object second)
System.Linq.Enumerable.Intersect[String] (IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)
System.Linq.Enumerable.Intersect[String] (IEnumerable`1 first, IEnumerable`1 second)
ProfileManager.GetActiveDisableList (ModType modType)
ModSelectorService.<Awake>m__D ()
APIProperties+Property.get_Value ()
APIProperties.get_Item (System.String key)
DynamicMissionGeneratorAssembly.MissionInputPage.ParseTextToMission (System.String text)
DynamicMissionGeneratorAssembly.MissionInputPage.RunInteract ()
ModSelectable.ProxyOnInteract ()
Selectable.HandleInteract ()
SelectableManager.HandleInteract ()
MouseControls.Interact ()
MouseControls.Update ()
```

Stack trace indicates the issue originates in the [Mod Selector mod](https://github.com/ashbash1987/ktanemod-modselector/blob/e6e9dbffeb917bf4d61a1bb45bf66bbd7a5dfacb/Assets/Scripts/ProfileManager.cs#L245) and suggests `ActiveDisableSet` is null at the time of execution.

I did not have any profiles set up in Mod Selector at the time. I set one up quickly and now running DMG missions works.

Not sure whether this should be considered a bug in this mod or Mod Selector - I'll defer to the owners of said mods on that.
