### ISSUE TITLE
Run button not working.

### ISSUE THREAD

**Issue by Obscure2020** [red031000/ktane-DynamicMissionGenerator#7]
New update just released to add custom mission saving, and some new mission definition features. Very cool.

However, these additions are useless if you can't actually RUN them.

Clicking the Run button does absolutely nothing on my computer.

**Comment by Obscure2020** [comment]
Wait, it's working now.
I'm unsure what caused it to start working, I've reloaded the game a few times.

**Comment by EuanMorgan** [comment]
Also having this issue
